package org.example;

import org.apache.poi.xwpf.usermodel.*;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Path;

public class ResumeFileExporter {
    public static Path exportUserResume(UserInfo user) {
        // output path — saves in Downloads folder
        Path outputPath = Path.of(
                System.getProperty("user.home"),
                "Downloads",
                user.getName().replaceAll("\\s+", "_") + "_Resume.docx"
        );

        try (XWPFDocument doc = new XWPFDocument()) {
            // ===== HEADER =====
            XWPFParagraph header = doc.createParagraph();
            header.setAlignment(ParagraphAlignment.CENTER);

            XWPFRun titleRun = header.createRun();
            titleRun.setBold(true);
            titleRun.setFontSize(20);
            titleRun.setText(user.getName());
            titleRun.addBreak();

            XWPFRun contactRun = header.createRun();
            contactRun.setFontSize(12);
            contactRun.setText(user.getCityState() + " | " + user.getEmail() + " | " + user.getPhone());
            contactRun.addBreak();
            contactRun.addBreak();

            // ===== ABOUT SECTION =====
            XWPFParagraph aboutHeader = doc.createParagraph();
            XWPFRun aboutTitle = aboutHeader.createRun();
            aboutTitle.setBold(true);
            aboutTitle.setFontSize(14);
            aboutTitle.setText("About Me");
            aboutTitle.addBreak();

            XWPFRun aboutText = aboutHeader.createRun();
            aboutText.setText(user.getAbout());
            aboutText.addBreak();
            aboutText.addBreak();

            // ===== QUALIFICATIONS =====
            XWPFParagraph qualHeader = doc.createParagraph();
            XWPFRun qualTitle = qualHeader.createRun();
            qualTitle.setBold(true);
            qualTitle.setFontSize(14);
            qualTitle.setText("Qualifications");
            qualTitle.addBreak();

            XWPFRun qualText = qualHeader.createRun();
            qualText.setText(user.getQuals());
            qualText.addBreak();

            // ===== FOOTER =====
            XWPFParagraph footer = doc.createParagraph();
            footer.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun footerRun = footer.createRun();
            footerRun.setFontSize(10);
            footerRun.setColor("808080");
            footerRun.setText("Generated by HackQU AI Resume Builder");

            // ===== WRITE TO FILE =====
            try (FileOutputStream out = new FileOutputStream(outputPath.toFile())) {
                doc.write(out);
            }

            System.out.println("Resume saved to: " + outputPath);
            return outputPath;

        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
}
